### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by 121zzy** [zmoka-zht/CDMamba#4]
Traceback (most recent call last):
  File "/exp/home/zhongyu.zhang/project/CDMamba/train_cd.py", line 70, in <module>
    cd_model = Model.create_CD_model(opt)
  File "/exp/home/zhongyu.zhang/project/CDMamba/models/__init__.py", line 26, in create_CD_model
    from models.CDMamba import CDMamba as cdmamba
  File "/exp/home/zhongyu.zhang/project/CDMamba/models/CDMamba.py", line 14, in <module>
    from mamba_ssm import Mamba as Mamba_ssm
  File "/exp/home/zhongyu.zhang/anaconda3/envs/cd_mamba/lib/python3.10/site-packages/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/exp/home/zhongyu.zhang/anaconda3/envs/cd_mamba/lib/python3.10/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 16, in <module>
    import selective_scan_cuda
ImportError: /exp/home/zhongyu.zhang/anaconda3/envs/cd_mamba/lib/python3.10/site-packages/selective_scan_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c107WarningC1ESt7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEERKNS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb

**Comment by zmoka-zht** [comment]
Please refer to https://blog.csdn.net/weixin_45667052/article/details/136311600.
